### PR TITLE
fix(withIntl): testcases fail on older React versions

### PR DESCRIPTION
**Pull request by scottdickerson**
fix(package.json): shouldn't use npm to install react versions because it will create a package-lock.json
test(withIntl.js): protect the assertion based on the current React version

### CODE REVIEW

**Comment by scottdickerson** [comment]
@DragonRaider5 here you go

**Comment by scottdickerson** [comment]
This is a difference in the renderer versions between React versions.  The react-addons-test-utils@^0.14, doesn't render components in the same way as the later react-test-renderer@^15 packages, so you don't get the actual React component instance returned, you get the dom instance.

**Comment by DragonRaider5** [comment]
You're absolutely right.

Still I think that simply avoiding the test case doesn't help as much, as by doing so we have no test coverage for `react` versions < 16. We'd need to write an alternative test using the old `enzyme` API.

**Comment by scottdickerson** [comment]
@DragonRaider5 ok I figured it out and made the changes where the test works on all the versions.  Please take a look!

**Pull request merged**
