### PR TITLE
fix(package.json): have to use yarn to install the react versions or deps break

### PR DESCRIPTION
**Pull request by scottdickerson**
fix(package.json): switched `npm i` to `yarn add`
Since the entire repo has migrated to yarn for package management, I had to remove the embedded "npm i" in package.json to use yarn instead.  Afterwards the test suites for both 14 and 15 executed successfully.

### CODE REVIEW

**Comment by scottdickerson** [comment]
@DragonRaider5 does this look ok?

**Comment by DragonRaider5** [comment]
Looks awesome, thanks! I'm surprised it was that easy... Shall we also remove the `package-lock.json` in favor of `yarn.lock`?

**Comment by DragonRaider5** [comment]
Just one problem: My `master` branch doesn't contain the changes I made - those are in `feature/new-context-api` so this might be a completely different story.

**Comment by scottdickerson** [comment]
you're right @DragonRaider5 , I see the other issues now...  will submit a new PR

**Pull request closed without merging**
